name: "HTTPTests Runner"
description: "Automated HTTP integration testing with Docker isolation - test APIs, proxies, and microservices in CI/CD"
author: "HTTPTests"
branding:
  icon: "check-circle"
  color: "green"

inputs:
  working-directory:
    description: "Directory to start scanning from"
    required: false
    default: "."
  python-version:
    description: "Python version to use"
    required: false
    default: "3.x"

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip -q
        pip install PyYAML requests -q

    - name: Generate and run suites
      shell: bash
      env:
        WORKDIR: ${{ inputs.working-directory }}
      run: |
        set -euo pipefail

        scan_root="${WORKDIR}"
        echo "Scanning for .httptests under: ${scan_root}"

        mapfile -t suites < <(find "${scan_root}" -type d -name .httptests | sort)
        if [[ ${#suites[@]} -eq 0 ]]; then
          echo "No .httptests directories found under ${scan_root}. Exiting."
          exit 1
        fi

        # Ensure generator is available
        gen_script_path="${GITHUB_ACTION_PATH}/generate_docker_compose.py"
        echo "Using generator: ${gen_script_path}"

        status_overall=0

        for suite_dir in "${suites[@]}"; do
          echo -e "\n=== Processing suite: ${suite_dir} ==="
          suite_parent="$(dirname "${suite_dir}")"
          compose_file="${suite_dir}/docker-compose.yml"
          test_file="${suite_dir}/test.json"
          
          # Generate project name, handling edge cases
          suffix="$(echo "${suite_parent}" | tr '/\\' '_' | tr -cd '[:alnum:]_-' | tr '[:upper:]' '[:lower:]' | sed 's/[_-]*$//' | sed 's/^[_-]*//')"
          if [[ -z "${suffix}" || "${suffix}" == "." ]]; then
            project_name="httptests"
          else
            project_name="httptests-${suffix}"
          fi

          if [[ ! -f "${test_file}" ]]; then
            echo "Warning: Missing test.json in ${suite_dir}, skipping."
            continue
          fi

          python "${gen_script_path}" \
            --suite "${suite_dir}" \
            --output "${compose_file}" > /dev/null 2>&1 || { echo "Compose generation failed"; status_overall=1; continue; }

          docker compose -f "${compose_file}" -p "${project_name}" up -d --build > /dev/null 2>&1

          sleep 5

          echo "Running tests for ${project_name}"
          python "${GITHUB_ACTION_PATH}/main.py" --test-file "${test_file}" || status_overall=$?

          docker compose -f "${compose_file}" -p "${project_name}" down -v > /dev/null 2>&1
        done

        exit ${status_overall}

